apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fileapi
  template:
    metadata:
      labels:
        app: fileapi
    spec:
      containers:
      - name: fileapi-container
        image: radhey24h/fileapi:0.0.1
        ports:
        - containerPort: 3202
        env:
          - name: PORT
            value: 3202
          - name: NODE_ENV
            value: "qa"

---
apiVersion: v1
kind: Service
metadata:
  name: fileapi-service
spec:
  selector:
    app: fileapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3202
  type: ClusterIP
