name: Docker FileManagement CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/services/fileManagement/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/services/fileManagement/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx for better platform support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} # Or DOCKERHUB_PASSWORD

    # Set the version number and create the image tag
    - name: Set Image Tag
      run: |
        VERSION="1.0.0"  # Set your version here
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
        IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/fileManagement:${VERSION}-${SHORT_SHA}"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Build the Docker image
    - name: Build the Docker image
      run: docker build ./backend/services/fileManagement --file backend/services/fileManagement/Dockerfile --tag ${{ env.IMAGE_TAG }}
      
    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}
