name: Docker Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx for better platform support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Set the version number and create the image tag dynamically
    - name: Set Image Tag
      run: |
        PIPELINE_VERSION_FILE="version-frontend.txt"  # Change this for each pipeline as needed
        
        # Check if the version file exists, create or increment version based on pipeline logic
        if [ -f $PIPELINE_VERSION_FILE ]; then
          VERSION=$(cat $PIPELINE_VERSION_FILE)
          VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1} 1' | sed 's/ /./g')
        else
          VERSION="1.0"  # Initialize with the base version for the pipeline
        fi
        
        echo $VERSION > $PIPELINE_VERSION_FILE
        IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/user:frontend-${VERSION}"
        
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build the Docker image
    - name: Build the Docker image
      run: docker build ./frontend --file frontend/Dockerfile --tag ${{ env.IMAGE_TAG }}
      
    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}

    # Commit and push the updated version file back to the repository
    - name: Commit version increment
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add $PIPELINE_VERSION_FILE
        git commit -m "Increment version to ${{ env.VERSION }} for frontend pipeline"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
