name: Docker Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/services/frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/services/frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx for better platform support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} # Or DOCKERHUB_PASSWORD

    # Build the Docker image
    - name: Build the Docker image
      run: docker build ./backend/services/frontend --file backend/services/frontend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$(date +%s)
      
    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$(date +%s)
