name: Docker Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx for better platform support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} # Or DOCKERHUB_PASSWORD

    # Get the short Git commit SHA and assign it to IMAGE_TAG
    - name: Get the Git commit SHA
      run: echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}" >> $GITHUB_ENV

    # Build the Docker image using the Git commit SHA as the tag
    - name: Build the Docker image
      run: docker build ./frontend --file frontend/Dockerfile --tag ${{ env.IMAGE_TAG }}
      
    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}
