name: Docker User CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/services/user/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'backend/services/user/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx for better platform support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} # Or DOCKERHUB_PASSWORD

    # Set the version number and create the image tag dynamically
    - name: Set Image Tag
      run: |
        if [ -f version.txt ]; then
          VERSION=$(cat version.txt)
          VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1} 1' | sed 's/ /./g')
        else
          VERSION="1.0"
        fi
        
        echo $VERSION > version.txt
        IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/user:${VERSION}"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Build the Docker image
    - name: Build the Docker image
      run: docker build ./backend/services/user --file backend/services/user/Dockerfile --tag ${{ env.IMAGE_TAG }}
      
    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}

    # Commit and push the updated version file back to the repository
    - name: Commit version increment
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add version.txt
        git commit -m "Increment version to ${{ env.VERSION }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT if the default token doesn't work

